name: your_env_name
channels:
  - defaults
dependencies:
  - python=3.8  # specify your Python version here
  - pip
  - numpy=1.24.4
  - matplotlib=3.7.2
  - pillow=10.0.0
  - pyyaml=6.0.1
  - scikit-image=0.19.3
  - scipy=1.6.3
  - pip:
      - einops==0.6.1
      - ema_pytorch==0.2.3
      - opencv-python==4.6.0.66
      - opencv-python-headless==4.8.0.74
      - termcolor==2.3.0
      - torch==2.0.1
      - torchvision==0.15.2
      - tqdm==4.65.0
